### ISSUE TITLE
Possible to make lazyrmd agnostic to output format?

### ISSUE THREAD

**Issue by cpsievert** [hafen/lazyrmd#11]
Would be possible to remove the requirement of using `lazyrmd::lazy_render` as the rendering function as the README suggests? It would be so awesome if I could enable this in bookdown...

**Comment by hafen** [comment]
This would be great - we'll look into it!

**Comment by schloerke** [comment]
fixed with lazy_render

**Comment by schloerke** [comment]
@cpsievert 

original:

``` yaml
output:
  bookdown::gitbook:
    lib_dir: "book_assets"
```

... wouldn't this be possible to do 

``` yaml
output:
  lazyrmd::lazy_render:
    lazyrmd_render_fn: gitbook
    lazyrmd_render_package: bookdown
    lib_dir: "book_assets"
```
